#!/usr/bin/env sh
# Created by Sema Demir 
# Faraday Networks
# email:sema.demir@faraday.net
# Date 24.03.2019 19:21:00

linuxne(){

if [ -f /etc/os-release ]; then
 # freedesktop.org and systemd
 . /etc/os-release
 OS=$NAME
 VER=$VERSION_ID

elif type lsb_release >/dev/null 2>&1; then
 #linuxbase.org
 OS=$(lsb_release -si)
 VER=$(lsb_release -sr)

elif [ -f /etc/lsb-release ]; then
 # For some versions of Debian/Ubuntu without lsb_release command
 . /etc/lsb-release
 OS=$DISTRIB_ID
 VER=$DISTRIB_RELEASE

elif [ -f /etc/debian_version ]; then
 # Older Debian/Ubuntu/etc.
 OS=Debian
 VER=$(cat /etc/debian_version)

elif [ -f /etc/SuSe-release ]; then
 # Older SuSE/etc.
 OS=SuSe

elif [ -f /etc/redhat-release ]; then
 # Older Red Hat, CentOS, etc.
 OS=Red Hat

else
 # Fall back to uname, e.g. "Linux <version>", also works for BSD, etc.
 OS=$(uname -s)
 VER=$(uname -r)

fi

if [ "$OS" == "CentOS Linux" ]; then
echo "sistem:"$OS
     yum install salt-api
     yum install salt-cloud
     yum install salt-master
     yum install salt-ssh
     yum install salt-syndic
     curl -L https://bootstrap.saltstack.com -o install_salt.sh
     sudo sh install_salt.sh -P -M -N
fi

if [ "$OS" == "Debian Linux" ]; then
     echo "sistem:"$OS
     apt-get install salt-api
     apt-get install salt-cloud
     apt-get install salt-master
     apt-get install salt-ssh
     apt-get install salt-syndic
     curl -L https://bootstrap.saltstack.com -o install_salt.sh
     sudo sh install_salt.sh -P -M -N
fi

if [ "$OS" == "Ubuntu Linux" ]; then
     echo "sistem:"$OS
     apt-get install salt-api
     apt-get install salt-cloud
     apt-get install salt-master
     apt-get install salt-ssh
     apt-get install salt-syndic
     curl -L https://bootstrap.saltstack.com -o install_salt.sh
     sudo sh install_salt.sh -P -M -N
fi

}

goster(){
echo "sema demir"
}

main(){
goster
linuxne
}
